# Automated Benchmark Configuration for IEEE-CIS Fraud Detection Project

# Dataset Configuration
dataset_path: "data/sample_fraud_data.csv"
target_column: "isFraud"
test_size: 0.2

# Models to Test
models_to_test:
  - "lightgbm"
  - "xgboost" 
  - "catboost"
  - "random_forest"

# Output Configuration
output_directory: "benchmark_results"
visualization_directory: "benchmark_visualizations"

# Performance Thresholds (for alerts)
max_training_time_minutes: 30.0
min_roc_auc: 0.85
max_inference_latency_ms: 100.0
min_throughput_per_second: 100

# Regression Detection
enable_regression_detection: true
regression_threshold_percent: 5.0  # 5% regression threshold
historical_results_keep_days: 30

# Automation Settings
enable_scheduled_runs: false
schedule_cron: "0 2 * * *"  # Daily at 2 AM
enable_alerts: true

# Alert Configuration
alert_webhook_url: null  # Set to your Slack webhook URL
alert_email_recipients: []  # Add email addresses for alerts

# Advanced Configuration
benchmark_modes:
  quick_test:
    models_to_test: ["lightgbm", "xgboost"]
    max_training_time_minutes: 10.0
    sample_size: 10000
  
  full_benchmark:
    models_to_test: ["lightgbm", "xgboost", "catboost", "random_forest"]
    max_training_time_minutes: 60.0
    include_optimization_tests: true
  
  production_validation:
    models_to_test: ["lightgbm"]  # Best performing model
    min_roc_auc: 0.90
    max_inference_latency_ms: 50.0
    min_throughput_per_second: 500

# Visualization Settings
visualization_config:
  create_executive_dashboard: true
  create_detailed_reports: true
  generate_comparison_matrix: true
  save_performance_trends: true

# CI/CD Integration
ci_cd_config:
  fail_on_regression: true
  fail_on_threshold_violation: true
  generate_github_summary: true
  upload_artifacts: true